#!/bin/bash

radio_domain -i 100_wl0 -o 200_wl0 &
RADIO_100_PID=$!
radio_domain -i 200_wl0 -o 100_wl0 &
RADIO_200_PID=$!

sleep 0.3

echo Starting launches at `date +%T.%N`

./system_peer --topology 2,2,2 --firstaddr 3,3,3 \
              -p 100 -i wl0 -a wl0,200,wl0,2000 \
              -t addtag,300,300 \
              \
              -t update_proxy_endpoint,305,0,3,100_0 \
              -t update_proxy_endpoint,305,0,2,100_0 \
              -t update_proxy_endpoint,305,0,1,100_0 \
              -t update_propagation_endpoint,305,0,3, \
              -t update_propagation_endpoint,305,0,2, \
              -t update_propagation_endpoint,305,0,1, \
              \
              -t add_identityarc,400,0,0+0 \
              \
              -t addtag,5300,5300 \
              -t add_identity,5400,0,1,3,0+0 \
              -t add_gateway,5420,1,0+0,0,2,-1 \
              -t update_n_nodes,5440,1,2 \
              -t update_coord_n_nodes,5440,1,2 \
              -t enter_net,5460,0,1,0,1:0:0,1:0:0,200:200:200 \
              > test_first_pid100_out.txt 2>&1 &
PEER_100_PID=$!

./system_peer --topology 2,2,2 --firstaddr 2,0,0 \
              -p 200 -i wl0 -a wl0,100,wl0,2000 \
              -t addtag,300,300 \
              \
              -t update_proxy_endpoint,305,0,3,200_0 \
              -t update_proxy_endpoint,305,0,2,200_0 \
              -t update_proxy_endpoint,305,0,1,200_0 \
              -t update_propagation_endpoint,305,0,3, \
              -t update_propagation_endpoint,305,0,2, \
              -t update_propagation_endpoint,305,0,1, \
              \
              -t add_identityarc,400,0,0+0 \
              \
              -t addtag,5300,5300 \
              -t add_identityarc,5400,0,0+1 \
              -t add_gateway,5420,0,0+1,0,1,-1 \
              -t update_n_nodes,5440,0,2 \
              -t update_coord_n_nodes,5440,0,2 \
              > test_first_pid200_out.txt 2>&1 &
PEER_200_PID=$!

echo Done launches at `date +%T.%N`

sleep 8

echo checking status...
PEER_ABORT=0
kill -0 $PEER_100_PID || { wait $PEER_100_PID; echo system_peer 100 prematurely exited with $?; PEER_ABORT=1; }
kill -0 $PEER_200_PID || { wait $PEER_200_PID; echo system_peer 200 prematurely exited with $?; PEER_ABORT=1; }

echo killing...
# interrupt peers
kill $PEER_100_PID $PEER_200_PID

wait $PEER_100_PID $PEER_200_PID

# Ignore errors in this shutdown. Remove any remaining local socket.
rm -f conn_169.254.*
rm -f conn_???_?
rm -f recv_???_wl0

# kill proxy demons
kill $RADIO_100_PID $RADIO_200_PID

wait $RADIO_100_PID $RADIO_200_PID

# delay for removal of local sockets (e.g. send_100_wl0)
sleep 0.3

# check PEER_ABORT
test $PEER_ABORT -eq 0 || exit 1
