#!/bin/bash

radio_domain -i 100_wl0 -o 200_wl0 -o 110_wl0 &
RADIO_100_PID=$!
radio_domain -i 200_wl0 -o 100_wl0 -o 210_wl0 &
RADIO_200_PID=$!
radio_domain -i 110_wl0 -o 210_wl0 -o 100_wl0 &
RADIO_110_PID=$!
radio_domain -i 210_wl0 -o 110_wl0 -o 200_wl0 &
RADIO_210_PID=$!

sleep 0.3

echo Starting launches at `date +%T.%N`

./system_peer --topology 2,2,2 --firstaddr 3,3,3 \
              \
              -p 100 -i wl0 \
              -a wl0,200,wl0,2000 \
              -a wl0,110,wl0,2000 \
              \
              -t add_identity,100,0,1,3,0+0 \
              -t enter_net,1000,0,1,0,1:0:0,1:0:0,200:200:200 \
              \
              -t add_identityarc,2000,1,1+1 \
              \
              > test_second_pid100_out.txt 2>&1 &
PEER_100_PID=$!

./system_peer --topology 2,2,2 --firstaddr 2,0,0 \
              \
              -p 200 -i wl0 \
              -a wl0,100,wl0,2000 \
              -a wl0,210,wl0,2000 \
              \
              -t add_identityarc,1000,0,0+1 \
              \
              -t add_identityarc,2000,0,1+2 \
              \
              > test_second_pid200_out.txt 2>&1 &
PEER_200_PID=$!

./system_peer --topology 2,2,2 --firstaddr 1,3,3 \
              \
              -p 110 -i wl0 \
              -a wl0,210,wl0,2000 \
              -a wl0,100,wl0,2000 \
              \
              -t add_identityarc,1000,0,0+1 \
              \
              -t add_identity,1100,0,2,3,0+2_1+1 \
              -t enter_net,2000,0,1,1,1:0,1:0,200:200 \
              \
              > test_second_pid110_out.txt 2>&1 &
PEER_110_PID=$!

./system_peer --topology 2,2,2 --firstaddr 2,0,0 \
              \
              -p 210 -i wl0 \
              -a wl0,110,wl0,2000 \
              -a wl0,200,wl0,2000 \
              \
              -t add_identity,100,0,1,3,0+0 \
              -t enter_net,1000,0,1,0,2:3:3,1:0:0,110:110:110 \
              \
              -t add_identity,1100,1,2,3,0+1_1+0 \
              -t enter_net,2000,1,2,1,1:0,1:0,200:200 \
              \
              > test_second_pid210_out.txt 2>&1 &
PEER_210_PID=$!

echo Done launches at `date +%T.%N`

sleep 5

echo checking status...
PEER_ABORT=0
kill -0 $PEER_100_PID || { wait $PEER_100_PID; echo system_peer 100 prematurely exited with $?; PEER_ABORT=1; }
kill -0 $PEER_200_PID || { wait $PEER_200_PID; echo system_peer 200 prematurely exited with $?; PEER_ABORT=1; }
kill -0 $PEER_110_PID || { wait $PEER_110_PID; echo system_peer 110 prematurely exited with $?; PEER_ABORT=1; }
kill -0 $PEER_210_PID || { wait $PEER_210_PID; echo system_peer 210 prematurely exited with $?; PEER_ABORT=1; }

echo killing...
# interrupt peers
kill $PEER_100_PID $PEER_200_PID $PEER_110_PID $PEER_210_PID

wait $PEER_100_PID $PEER_200_PID $PEER_110_PID $PEER_210_PID

# Ignore errors in this shutdown. Remove any remaining local socket.
rm -f conn_169.254.*
rm -f conn_???_?
rm -f recv_???_wl0

# kill proxy demons
kill $RADIO_100_PID $RADIO_200_PID $RADIO_110_PID $RADIO_210_PID

wait $RADIO_100_PID $RADIO_200_PID $RADIO_110_PID $RADIO_210_PID

# delay for removal of local sockets (e.g. send_100_wl0)
sleep 0.3

# check PEER_ABORT
test $PEER_ABORT -eq 0 || exit 1
