#!/bin/bash

radio_domain -i 2232_wl0 -o 3122_wl0 -o 2322_wl0 &
RADIO_2232_PID=$!
radio_domain -i 3122_wl0 -o 2232_wl0 -o 2322_wl0 -o 1012_wl0 -o 2122_wl0 &
RADIO_3122_PID=$!
radio_domain -i 2322_wl0 -o 2232_wl0 -o 3122_wl0 -o 1012_wl0 &
RADIO_2322_PID=$!
radio_domain -i 1012_wl0 -o 2322_wl0 -o 3122_wl0 -o 2012_wl0 &
RADIO_1012_PID=$!
radio_domain -i 2122_wl0 -o 3122_wl0 -o 2312_wl0 &
RADIO_2122_PID=$!
radio_domain -i 2012_wl0 -o 1012_wl0 -o 3312_wl0 &
RADIO_2012_PID=$!
radio_domain -i 3312_wl0 -o 2012_wl0 -o 2312_wl0 &
RADIO_3312_PID=$!
radio_domain -i 2312_wl0 -o 3312_wl0 -o 2122_wl0 &
RADIO_2312_PID=$!

radio_domain -i 1333_wl0 -o 2233_wl0 &
RADIO_1333_PID=$!
radio_domain -i 2233_wl0 -o 1333_wl0 -o 1233_wl0 &
RADIO_2233_PID=$!
radio_domain -i 1233_wl0 -o 2233_wl0 -o 2133_wl0 &
RADIO_1233_PID=$!
radio_domain -i 2133_wl0 -o 1233_wl0 -o 1133_wl0 &
RADIO_2133_PID=$!
radio_domain -i 1133_wl0 -o 2133_wl0 &
RADIO_1133_PID=$!

sleep 0.3

echo Starting launches at `date +%T.%N`

./system_peer --topology 2,2,2,2 --firstaddr 2,2,3,2 \
              \
              -p 2232 -i wl0 \
              -a wl0,3122,wl0,2000 \
              -a wl0,2322,wl0,2000 \
              \
              -t add_identityarc,200,0,0+1 \
              \
              -t add_identityarc,500,0,1+1 \
              \
              -t add_gateway,2000,0,0+1,2,2,-1 \
              -t add_gateway,2000,0,0+1,2,1,-1 \
              -t add_gateway,2002,0,1+1,2,2,-1 \
              -t add_gateway,2002,0,1+1,2,1,-1 \
              -t update_n_nodes,2000,0,8 \
              -t update_coord_n_nodes,2000,0,8 \
              -t update_proxy_endpoint,2000,0,4,1012_1 \
              -t update_proxy_endpoint,2000,0,3,1012_1 \
              -t update_proxy_endpoint,2000,0,2,2232_0 \
              -t update_proxy_endpoint,2000,0,1,2232_0 \
              -t update_propagation_endpoint,2000,0,4,2322_1+3122_1+2122_1+1012_1+2012_1+3312_1+2312_1 \
              -t update_propagation_endpoint,2000,0,3,2322_1+3122_1+2122_1+1012_1+2012_1+3312_1+2312_1 \
              -t update_propagation_endpoint,2000,0,2, \
              -t update_propagation_endpoint,2000,0,1, \
              \
              > test_second_pid2232_out.txt 2>&1 &
PEER_2232_PID=$!

./system_peer --topology 2,2,2,2 --firstaddr 3,1,2,2 \
              \
              -p 3122 -i wl0 \
              -a wl0,2232,wl0,2000 \
              -a wl0,2322,wl0,2000 \
              -a wl0,1012,wl0,2000 \
              -a wl0,2122,wl0,2000 \
              \
              -t add_identity,100,0,1,4,0+0 \
              -t enter_net,300,0,1,0,2:2,1:0,2232:2232 \
              \
              -t add_identityarc,500,1,1+1 \
              \
              -t add_identityarc,800,1,2+1 \
              \
              -t add_identityarc,800,1,3+1 \
              \
              -t add_gateway,2000,1,3+1,0,2,-1 \
              -t add_gateway,2000,1,1+1,1,3,-1 \
              -t add_gateway,2000,1,0+0,2,3,-1 \
              -t add_gateway,2000,1,2+1,2,1,-1 \
              -t add_gateway,2002,1,1+1,2,1,-1 \
              -t add_gateway,2004,1,3+1,2,1,-1 \
              -t update_n_nodes,2000,1,8 \
              -t update_coord_n_nodes,2000,1,8 \
              -t update_proxy_endpoint,2000,1,4,1012_1 \
              -t update_proxy_endpoint,2000,1,3,1012_1 \
              -t update_proxy_endpoint,2000,1,2,2122_1 \
              -t update_proxy_endpoint,2000,1,1,2122_1 \
              -t update_propagation_endpoint,2000,1,4,2322_1+2122_1+1012_1+2012_1+3312_1+2312_1+2232_0 \
              -t update_propagation_endpoint,2000,1,3,2322_1+2122_1+1012_1+2012_1+3312_1+2312_1+2232_0 \
              -t update_propagation_endpoint,2000,1,2,2122_1+2322_1 \
              -t update_propagation_endpoint,2000,1,1,2122_1 \
              \
              > test_second_pid3122_out.txt 2>&1 &
PEER_3122_PID=$!

./system_peer --topology 2,2,2,2 --firstaddr 2,3,2,2 \
              \
              -p 2322 -i wl0 \
              -a wl0,2232,wl0,2000 \
              -a wl0,3122,wl0,2000 \
              -a wl0,1012,wl0,2000 \
              \
              -t add_identity,400,0,1,4,0+0_1+1 \
              -t enter_net,600,0,1,0,3:2:2,1:0:0,3122:2232:2232 \
              \
              -t add_identityarc,800,1,2+1 \
              \
              > test_second_pid2322_out.txt 2>&1 &
PEER_2322_PID=$!

./system_peer --topology 2,2,2,2 --firstaddr 1,0,1,2 \
              \
              -p 1012 -i wl0 \
              -a wl0,2322,wl0,2000 \
              -a wl0,3122,wl0,2000 \
              -a wl0,2012,wl0,2000 \
              \
              -t add_identity,700,0,1,4,0+1_1+1 \
              -t enter_net,900,0,1,0,1:2,2:0,2232:2232 \
              \
              -t add_identityarc,1100,1,2+1 \
              \
              > test_second_pid1012_out.txt 2>&1 &
PEER_1012_PID=$!

./system_peer --topology 2,2,2,2 --firstaddr 2,1,2,2 \
              \
              -p 2122 -i wl0 \
              -a wl0,3122,wl0,2000 \
              -a wl0,2312,wl0,2000 \
              \
              -t add_identity,700,0,1,4,0+1 \
              -t enter_net,900,0,1,0,2:1:2:2,1:0:1:0,3122:3122:2232:2232 \
              \
              -t add_identityarc,1700,1,1+1 \
              \
              > test_second_pid2122_out.txt 2>&1 &
PEER_2122_PID=$!

./system_peer --topology 2,2,2,2 --firstaddr 2,0,1,2 \
              \
              -p 2012 -i wl0 \
              -a wl0,1012,wl0,2000 \
              -a wl0,3312,wl0,2000 \
              \
              -t add_identity,1000,0,1,4,0+1 \
              -t enter_net,1200,0,1,0,2:0:1:2,1:0:2:0,1012:1012:2232:2232 \
              \
              -t add_identityarc,1400,1,1+1 \
              \
              > test_second_pid2012_out.txt 2>&1 &
PEER_2012_PID=$!

./system_peer --topology 2,2,2,2 --firstaddr 3,3,1,2 \
              \
              -p 3312 -i wl0 \
              -a wl0,2012,wl0,2000 \
              -a wl0,2312,wl0,2000 \
              \
              -t add_identity,1300,0,1,4,0+1 \
              -t enter_net,1500,0,1,0,3:1:2,1:2:0,1012:2232:2232 \
              \
              -t add_identityarc,1700,1,1+1 \
              \
              > test_second_pid3312_out.txt 2>&1 &
PEER_3312_PID=$!

./system_peer --topology 2,2,2,2 --firstaddr 2,3,1,2 \
              \
              -p 2312 -i wl0 \
              -a wl0,3312,wl0,2000 \
              -a wl0,2122,wl0,2000 \
              \
              -t add_identity,1600,0,1,4,0+1_1+1 \
              -t enter_net,1800,0,1,0,2:3:1:2,1:1:2:0,3312:1012:2232:2232 \
              \
              > test_second_pid2312_out.txt 2>&1 &
PEER_2312_PID=$!



./system_peer --topology 2,2,2,2 --firstaddr 1,3,3,3 \
              \
              -p 1333 -i wl0 \
              -a wl0,2233,wl0,2000 \
              \
              -t add_identityarc,200,0,0+1 \
              \
              > test_second_pid1333_out.txt 2>&1 &
PEER_1333_PID=$!

./system_peer --topology 2,2,2,2 --firstaddr 2,2,3,3 \
              \
              -p 2233 -i wl0 \
              -a wl0,1333,wl0,2000 \
              -a wl0,1233,wl0,2000 \
              \
              -t add_identity,100,0,1,4,0+0 \
              -t enter_net,300,0,1,0,2:3:3,1:0:0,1333:1333:1333 \
              \
              -t add_identityarc,500,1,1+1 \
              \
              > test_second_pid2233_out.txt 2>&1 &
PEER_2233_PID=$!

./system_peer --topology 2,2,2,2 --firstaddr 1,2,3,3 \
              \
              -p 1233 -i wl0 \
              -a wl0,2233,wl0,2000 \
              -a wl0,2133,wl0,2000 \
              \
              -t add_identity,400,0,1,4,0+1 \
              -t enter_net,600,0,1,0,1:2:3:3,1:1:0:0,2233:1333:1333:1333 \
              \
              -t add_identityarc,800,1,1+1 \
              \
              > test_second_pid1233_out.txt 2>&1 &
PEER_1233_PID=$!

./system_peer --topology 2,2,2,2 --firstaddr 2,1,3,3 \
              \
              -p 2133 -i wl0 \
              -a wl0,1233,wl0,2000 \
              -a wl0,1133,wl0,2000 \
              \
              -t add_identity,700,0,1,4,0+1 \
              -t enter_net,900,0,1,0,1:3:3,2:0:0,1333:1333:1333 \
              \
              -t add_identityarc,1100,1,1+1 \
              \
              > test_second_pid2133_out.txt 2>&1 &
PEER_2133_PID=$!

./system_peer --topology 2,2,2,2 --firstaddr 1,1,3,3 \
              \
              -p 1133 -i wl0 \
              -a wl0,2133,wl0,2000 \
              \
              -t add_identity,1000,0,1,4,0+1 \
              -t enter_net,1200,0,1,0,1:1:3:3,1:2:0:0,2133:1333:1333:1333 \
              \
              > test_second_pid1133_out.txt 2>&1 &
PEER_1133_PID=$!

echo Done launches at `date +%T.%N`

sleep 5

echo checking status...
PEER_ABORT=0
kill -0 $PEER_2232_PID || { wait $PEER_2232_PID; echo system_peer 2232 prematurely exited with $?; PEER_ABORT=1; }
kill -0 $PEER_3122_PID || { wait $PEER_3122_PID; echo system_peer 3122 prematurely exited with $?; PEER_ABORT=1; }
kill -0 $PEER_2322_PID || { wait $PEER_2322_PID; echo system_peer 2322 prematurely exited with $?; PEER_ABORT=1; }
kill -0 $PEER_1012_PID || { wait $PEER_1012_PID; echo system_peer 1012 prematurely exited with $?; PEER_ABORT=1; }
kill -0 $PEER_2122_PID || { wait $PEER_2122_PID; echo system_peer 2122 prematurely exited with $?; PEER_ABORT=1; }
kill -0 $PEER_2012_PID || { wait $PEER_2012_PID; echo system_peer 2012 prematurely exited with $?; PEER_ABORT=1; }
kill -0 $PEER_3312_PID || { wait $PEER_3312_PID; echo system_peer 3312 prematurely exited with $?; PEER_ABORT=1; }
kill -0 $PEER_2312_PID || { wait $PEER_2312_PID; echo system_peer 2312 prematurely exited with $?; PEER_ABORT=1; }
#===
kill -0 $PEER_1333_PID || { wait $PEER_1333_PID; echo system_peer 1333 prematurely exited with $?; PEER_ABORT=1; }
kill -0 $PEER_2233_PID || { wait $PEER_2233_PID; echo system_peer 2233 prematurely exited with $?; PEER_ABORT=1; }
kill -0 $PEER_1233_PID || { wait $PEER_1233_PID; echo system_peer 1233 prematurely exited with $?; PEER_ABORT=1; }
kill -0 $PEER_2133_PID || { wait $PEER_2133_PID; echo system_peer 2133 prematurely exited with $?; PEER_ABORT=1; }
kill -0 $PEER_1133_PID || { wait $PEER_1133_PID; echo system_peer 1133 prematurely exited with $?; PEER_ABORT=1; }

echo killing...
# interrupt peers
kill $PEER_2232_PID $PEER_3122_PID $PEER_2322_PID $PEER_1012_PID $PEER_2122_PID $PEER_2012_PID \
     $PEER_3312_PID $PEER_2312_PID
kill $PEER_1333_PID $PEER_2233_PID $PEER_1233_PID $PEER_2133_PID $PEER_1133_PID

wait $PEER_2232_PID $PEER_3122_PID $PEER_2322_PID $PEER_1012_PID $PEER_2122_PID $PEER_2012_PID \
     $PEER_3312_PID $PEER_2312_PID
wait $PEER_1333_PID $PEER_2233_PID $PEER_1233_PID $PEER_2133_PID $PEER_1133_PID

# Ignore errors in this shutdown. Remove any remaining local socket.
rm -f conn_169.254.*
rm -f conn_????_?
rm -f recv_????_wl0

# kill proxy demons
kill $RADIO_2232_PID $RADIO_3122_PID $RADIO_2322_PID $RADIO_1012_PID $RADIO_2122_PID $RADIO_2012_PID \
     $RADIO_3312_PID $RADIO_2312_PID
kill $RADIO_1333_PID $RADIO_2233_PID $RADIO_1233_PID $RADIO_2133_PID $RADIO_1133_PID

wait $RADIO_2232_PID $RADIO_3122_PID $RADIO_2322_PID $RADIO_1012_PID $RADIO_2122_PID $RADIO_2012_PID \
     $RADIO_3312_PID $RADIO_2312_PID
wait $RADIO_1333_PID $RADIO_2233_PID $RADIO_1233_PID $RADIO_2133_PID $RADIO_1133_PID

# delay for removal of local sockets (e.g. send_2232_wl0)
sleep 0.3

# check PEER_ABORT
test $PEER_ABORT -eq 0 || exit 1
