#!/bin/bash

radio_domain -i 2232_wl0 -o 3122_wl0 -o 2322_wl0 &
RADIO_2232_PID=$!
radio_domain -i 3122_wl0 -o 2232_wl0 -o 2322_wl0 -o 1012_wl0 -o 2122_wl0 &
RADIO_3122_PID=$!
radio_domain -i 2322_wl0 -o 2232_wl0 -o 3122_wl0 -o 1012_wl0 &
RADIO_2322_PID=$!
radio_domain -i 1012_wl0 -o 2322_wl0 -o 3122_wl0 &
RADIO_1012_PID=$!
radio_domain -i 2122_wl0 -o 3122_wl0 &
RADIO_2122_PID=$!

sleep 0.3

echo Starting launches at `date +%T.%N`

./system_peer --topology 2,2,2,2 --firstaddr 2,2,3,2 \
              \
              -p 2232 -i wl0 \
              -a wl0,3122,wl0,2000 \
              -a wl0,2322,wl0,2000 \
              \
              -t add_identityarc,200,0,0+1 \
              \
              -t add_identityarc,500,0,1+1 \
              \
              > test_second_pid2232_out.txt 2>&1 &
PEER_2232_PID=$!

./system_peer --topology 2,2,2,2 --firstaddr 3,1,2,2 \
              \
              -p 3122 -i wl0 \
              -a wl0,2232,wl0,2000 \
              -a wl0,2322,wl0,2000 \
              -a wl0,1012,wl0,2000 \
              -a wl0,2122,wl0,2000 \
              \
              -t add_identity,100,0,1,4,0+0 \
              -t enter_net,300,0,1,0,2:2,1:0,2232:2232 \
              \
              -t add_identityarc,500,1,1+1 \
              \
              -t add_identityarc,800,1,2+1 \
              \
              -t add_identityarc,800,1,3+1 \
              \
              > test_second_pid3122_out.txt 2>&1 &
PEER_3122_PID=$!

./system_peer --topology 2,2,2,2 --firstaddr 2,3,2,2 \
              \
              -p 2322 -i wl0 \
              -a wl0,2232,wl0,2000 \
              -a wl0,3122,wl0,2000 \
              -a wl0,1012,wl0,2000 \
              \
              -t add_identity,400,0,1,4,0+0_1+1 \
              -t enter_net,600,0,1,0,3:2:2,1:0:0,3122:2232:2232 \
              \
              -t add_identityarc,800,1,2+1 \
              \
              > test_second_pid2322_out.txt 2>&1 &
PEER_2322_PID=$!

./system_peer --topology 2,2,2,2 --firstaddr 1,0,1,2 \
              \
              -p 1012 -i wl0 \
              -a wl0,2322,wl0,2000 \
              -a wl0,3122,wl0,2000 \
              \
              -t add_identity,700,0,1,4,0+1_1+1 \
              -t enter_net,900,0,1,0,1:2,2:0,2232:2232 \
              \
              > test_second_pid1012_out.txt 2>&1 &
PEER_1012_PID=$!

./system_peer --topology 2,2,2,2 --firstaddr 2,1,2,2 \
              \
              -p 2122 -i wl0 \
              -a wl0,3122,wl0,2000 \
              \
              -t add_identity,700,0,1,4,0+1 \
              -t enter_net,900,0,1,0,2:1:2:2,1:0:1:0,3122:3122:2232:2232 \
              \
              > test_second_pid2122_out.txt 2>&1 &
PEER_2122_PID=$!

echo Done launches at `date +%T.%N`

sleep 5

echo checking status...
PEER_ABORT=0
kill -0 $PEER_2232_PID || { wait $PEER_2232_PID; echo system_peer 2232 prematurely exited with $?; PEER_ABORT=1; }
kill -0 $PEER_3122_PID || { wait $PEER_3122_PID; echo system_peer 3122 prematurely exited with $?; PEER_ABORT=1; }
kill -0 $PEER_2322_PID || { wait $PEER_2322_PID; echo system_peer 2322 prematurely exited with $?; PEER_ABORT=1; }
kill -0 $PEER_1012_PID || { wait $PEER_1012_PID; echo system_peer 1012 prematurely exited with $?; PEER_ABORT=1; }
kill -0 $PEER_2122_PID || { wait $PEER_2122_PID; echo system_peer 2122 prematurely exited with $?; PEER_ABORT=1; }

echo killing...
# interrupt peers
kill $PEER_2232_PID $PEER_3122_PID $PEER_2322_PID $PEER_1012_PID $PEER_2122_PID

wait $PEER_2232_PID $PEER_3122_PID $PEER_2322_PID $PEER_1012_PID $PEER_2122_PID

# Ignore errors in this shutdown. Remove any remaining local socket.
rm -f conn_169.254.*
rm -f conn_????_?
rm -f recv_????_wl0

# kill proxy demons
kill $RADIO_2232_PID $RADIO_3122_PID $RADIO_2322_PID $RADIO_1012_PID $RADIO_2122_PID

wait $RADIO_2232_PID $RADIO_3122_PID $RADIO_2322_PID $RADIO_1012_PID $RADIO_2122_PID

# delay for removal of local sockets (e.g. send_2232_wl0)
sleep 0.3

# check PEER_ABORT
test $PEER_ABORT -eq 0 || exit 1
